-- SNOWFLAKE_LEARNING_DB object definitions
-- Regenerate with: SELECT GET_DDL('DATABASE', 'SNOWFLAKE_LEARNING_DB', TRUE);
-- Paste the query result below this line.

create database if not exists SNOWFLAKE_LEARNING_DB COMMENT='Created by Snowflake during account provisioning';

create schema if not exists SNOWFLAKE_LEARNING_DB.ANKURLAMICHHANE11_LOAD_SAMPLE_DATA_FROM_S3;

create TABLE if not exists SNOWFLAKE_LEARNING_DB.ANKURLAMICHHANE11_LOAD_SAMPLE_DATA_FROM_S3.MENU (
	MENU_ID NUMBER(19,0),
	MENU_TYPE_ID NUMBER(38,0),
	MENU_TYPE VARCHAR(16777216),
	TRUCK_BRAND_NAME VARCHAR(16777216),
	MENU_ITEM_ID NUMBER(38,0),
	MENU_ITEM_NAME VARCHAR(16777216),
	ITEM_CATEGORY VARCHAR(16777216),
	ITEM_SUBCATEGORY VARCHAR(16777216),
	COST_OF_GOODS_USD NUMBER(38,4),
	SALE_PRICE_USD NUMBER(38,4),
	MENU_ITEM_HEALTH_METRICS_OBJ VARIANT
);